# Generated by Django 4.2.1 on 2023-05-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'discount_code',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pincode', models.CharField(default='000000', max_length=10)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('contact_no', models.CharField(blank=True, max_length=12, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.district')),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location_link', models.URLField()),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.state')),
            ],
            options={
                'db_table': 'tourist_place',
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('number_of_days', models.PositiveIntegerField(default=0)),
                ('number_of_nights', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_tour_packages', to='admin_module.discountcode')),
                ('hotels', models.ManyToManyField(related_name='admin_tour_packages', to='admin_module.hotel')),
                ('tourist_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.touristplace')),
            ],
            options={
                'db_table': 'admin_tour_package',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.state'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.state'),
        ),
    ]
