# Generated by Django 4.2.1 on 2023-05-19 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tourist_place_images')),
                ('caption', models.CharField(max_length=100)),
                ('tourist_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_module.touristplace')),
            ],
            options={
                'db_table': 'tourist_place_image',
            },
        ),
    ]
